INSERT INTO USUARIO  (ID, CURSO, EMAIL, GENERO, NOME, NOME_USUARIO, SENHA, SOBRENOME, UNIVERSIDADE) VALUES  (1000000, 'CiC', 'kilmer@email', 'M', 'Kilmer Luiz', 'kilmer', 'senha', 'Aleluia', 'UnB')
INSERT INTO USUARIO  (ID, CURSO, EMAIL, GENERO, NOME, NOME_USUARIO, SENHA, SOBRENOME, UNIVERSIDADE) VALUES  (2000000, 'CiC', 'iure@email', 'M', 'Iure', 'iure', 'senha', 'Brandao', 'UnB')
INSERT INTO USUARIO  (ID, CURSO, EMAIL, GENERO, NOME, NOME_USUARIO, SENHA, SOBRENOME, UNIVERSIDADE) VALUES  (3000000, 'CiC', 'victor@email', 'M', 'Victor', 'victor', 'senha', 'Dantas', 'UnB')

INSERT INTO DISCIPLINA (ID, NOME, DEPARTAMENTO, USUARIO_ID) VALUES (100, 'Estrutura de Dados', 'CiC', 1000000)
INSERT INTO DISCIPLINA (ID, NOME, DEPARTAMENTO, USUARIO_ID) VALUES (200, 'Sistemas de Informacao', 'CiC', 1000000)
